pp: testingapp
service: qnd-step-function-x

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  region: ${opt:region, 'us-east-1'}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - states:*
        - sns:*
      Resource:
        - "*"

functions:
  doSomethingStepOne:
    handler: handler.doSomethingStepOne
  doSomethingStepTwo:
    handler: handler.doSomethingStepTwo
  executeStepFunction:
    handler: handler.executeStepFunction
    events:
      - http:
          path: /step-function
          method: GET

stepFunctions:
  stateMachines:
    qndStateMachineOne:
      type: EXPRESS
      name: 'qndStateMachineOne'
      definition:
        Comment: "Simple sf example"
        StartAt: theFirstState
        States:
          theFirstState:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-doSomethingStepOne"
            Next: doSomethingStepTwo
          StateB:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-doSomethingStepTwo"
            End: true

plugins:
   - serverless-step-functions
   - serverless-pseudo-parameters
